Update aiohttp version constraint in pyproject.toml (#621)
* Update aiohttp version constraint in pyproject.toml

Apparently there was a breaking change in aiohttp 3.14, because I'm getting:

```
Traceback (most recent call last):
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/bin/sleamdge", line 4, in <module>
    from sleamdge import main
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/sleamdge/__init__.py", line 10, in <module>
    from . import command, config, contact, gateway, group, session
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/sleamdge/contact.py", line 6, in <module>
    import steam
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/lib/python3.12/site-packages/steam/__init__.py", line 19, in <module>
    from .client import *
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/lib/python3.12/site-packages/steam/client.py", line 54, in <module>
    from .state import ConnectionState
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/lib/python3.12/site-packages/steam/state.py", line 39, in <module>
    from .manifest import AppInfo, ContentServer, Manifest, PackageInfo
  File "/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/lib/python3.12/site-packages/steam/manifest.py", line 22, in <module>
    from aiohttp.streams import AsyncStreamReaderMixin
ImportError: cannot import name 'AsyncStreamReaderMixin' from 'aiohttp.streams' (/home/nicoco/src/perso/xmpp/slidge/modules/sleamdge/.venv/lib/python3.12/site-packages/aiohttp/streams.py)
```

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>